### ISSUE TITLE
Can't install iepy on Python 2

### ISSUE THREAD

**Issue by alonsopg** [machinalis/iepy#107]
I can not even install iepy in python 2:

```
user@MacBook-Pro-de-User:~$ pip install iepy
Collecting iepy
  Using cached iepy-0.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0d/_dh_7wv12m303zkx41bz1kq40000gn/T/pip-build-0Rvagz/iepy/setup.py", line 7, in <module>
        with open(path.join(HERE, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0d/_dh_7wv12m303zkx41bz1kq40000gn/T/pip-build-0Rvagz/iepy/
```

What can I do?...

**Comment by jmansilla** [comment]
Hi Alonso 

I'm sorry, but iepy only runs on python 3. (Yes, we should have a better error message, and we actually have it on development branch)


Since you are using MacOS, you may consider installing python 3 following these instructions
https://docs.python.org/3/using/mac.html#getting-and-installing-macpython

**Comment by alonsopg** [comment]
Hi jmansilla, I also tried to install it on Python3. Nevertheless, it did not worked... I am installing the dev version.
