### ISSUE TITLE
"No Evidence to Label"

### ISSUE THREAD

**Issue by GilJ** [machinalis/iepy#82]
I created a relation, and when I want to label some evidence about it, I receive the message that there is no evidence to label. I'm wondering if I am understanding IEPY wrong, or just doing something wrong.

What I'm doing is the following:
I have 200ish documents that I load up in IEPY with the bin/csv_to_iepy.py script.
My preprocessing consits out of 3 steps. In the first step I extract tokens out of the document text. The second step is a custom POS tagger, and the third step is a custom NER tagger (this one consists of reading a set of precomputed tags from a file, found using the documents human_identifier).
Besides setting tokenization, tagging and ner results, I'm not doing any other steps with the documents.

I currently have 3 NER tags: numbers, types (think type of a building) and spaces (think rooms of a building). I created a relation between numbers and spaces. Even though I have plenty of documents in which those tags occur together (multiple times even), I don't have any documents to label.

**Comment by GilJ** [comment]
If it can be of any help. I created a rule to extract the same type of information:
```python
# -*- coding: utf-8 -*-

from refo import Star, Any
from iepy.extraction.rules import rule

RELATION = "number_of_space"

@rule(True)
def number_before_space(Subject, Object):
    """
    Ex: There are 4 bedrooms available.
    """
    anything = Star(Any())
    return anything + Subject + Object + anything
```

The associated relation has a left entity of type 'number' and right entity of type 'space'.

Running ```python3 bin/rules_verifier.py "number_of_space"``` results in
```zsh
Loading candidate evidence from database...
Getting labels from DB
Sorting labels them by evidence
Labels conflict solving

Matches for rule 'number_before_space' (value: True)
----------------------------------------------------
  nothing matched
```

**Comment by francolq** [comment]
Not sure if this is the source of your problem, but I think you also need to do some kind of sentence segmentation ("sentencing").

**Comment by GilJ** [comment]
I added sentence segmentation (each document was given the sentence structure [0, len(doc.tokens)], so the whole document was 1 sentence), but that did not seem to fix my issue.

Looking at all of my steps, this is what I add to document in each of the document's preprocessing step:
Let's assume my document (toy example) is
```
The cake requires 4 eggs . You also need butter .
```

* The tokenizer results in
```python
[(0, 'The'), (4, 'cake'), (9, 'requires'), (18, '4'), (20, 'eggs'), (25, '.'), (27, 'You'), (31, 'also'), (36, 'need'), (41, 'butter'), (48, '.')]
```
This is then used in the IEDocument's ```set_tokenization_result``` method.

* The output of the POS tagger has the following format:
```python
['N', 'Punc', 'Adj', 'V', 'N', 'Prep', 'N', '-None-', 'Punc', 'N', '-None-', 'Punc', 'Num', 'Adj', 'N',
'-None-', 'Punc', 'Adv', 'Adj', ...]
```
This is not the output of the toy example POS tags, but is actually the result of applying a NLTK POS tagger trained on the Dutch CONLL2002 corpus.
The length of the POS tagger output is the same as the number of tokens in the document.

* The output of the NER step is a list of FoundEntities
```python
[FoundEntity(key='cake', kind_name='type', alias='cake', offset=1, offset_end=2, from_gazette=False),
FoundEntity(key='4', kind_name='number', alias='4', offset=3, offset_end=4, from_gazette=False),
FoundEntity(key='eggs', kind_name='ingredient', alias='eggs', offset=4, offset_end=5, from_gazette=False),
FoundEntity(key='butter', kind_name='ingredient', alias='butter', offset=9, offset_end=10, from_gazette=False)]
```

* As I said, the sentencer is rather 'naive', and the output for the toy example would be
```python
[0, 11]
```

These are the results I set trough the appropriate ```set``` methods on the IEDocument model.

**Comment by GilJ** [comment]
Apparently, I was missing the segments.

However, something that is also required to do annotate the evidence are the parsed sentences. For these however, I coulnd't find in the code how they had to look so I tried something, and now I can actually see documents to annotate, but I can't see their contents, so I'm assuming something is wrong.

Could anyone tell me what the correct format is of the syntactic parsing result?

**Comment by rafacarrascosa** [comment]
Hi Gilles, the format is a string like this:

    (ROOT (S (NP (DT The) (NN cat)) (VP (VBZ eats) (NP (NN fish))) (. .)))

Which is the Penn Treebank bracketing format for parse trees. It is not documented, it's true, sorry for that. If you want to play with more explamples of these kind of trees you can use this demo of CoreNLP: http://nlp.stanford.edu:8080/corenlp/

You can call `set_syntactic_parsing_result` with a string like that. If you want to fake/mock a syntactic parsing you can fake a shallow tree like this:

    (ROOT (X The) (X cat) (X eats) (X fish) (X .))

And nothing should break.

WRT to the sentencing/segmenting thingy: The amount of relation candidates will increase quadratically with the size of the segment (which is usually a sentence long), so if your documents are small you should have no problem but if your documents are large consider segmenting them with a different strategy.

**Comment by GilJ** [comment]
Hey @rafacarrascosa,

Thanks a lot, I passed the fake shallow tree like you suggested, but I'm not sure whether it worked.
When I create a relation, I can already go to the 'label evidence' part, but the page is empty:

![image](https://cloud.githubusercontent.com/assets/143378/8476101/20af84e0-20be-11e5-925f-da3fcc9ac71a.png)

Would this issue be related to my fake segmentation/parse trees?

**Comment by rafacarrascosa** [comment]
Mmm, looks like javascript witchery, what do you think @j0hn ?

**Comment by j0hn** [comment]
That looks like there's one sentence because i can see that the little tree icon is being displayed at the far right, if you click that, you should get a popup with the fake tree that you've set.

I'm not sure why it looks like there are no tokens on the sentence, i would check the database using the admin interface available in http://localhost:8000/admin
That might give you an idea of whether you're missing some data.

If not, you could share us you're sqlite database (assuming you are using sqlite) with the preprocessed data, so we can check why the sentences are not being displayed.

**Comment by GilJ** [comment]
I'd share my DB, but I'd prefer to fix it myself first, I'd need to create a DB with some toy examples instead of what I have now.

When looking at javascript errors, I get the following error when I want to label evidence for my relation:
```js
document_questions.js:371 Uncaught TypeError: Cannot read property 'top' of undefined
$scope.calculate_arrow_string @ document_questions.js:371
$scope.update_relations_arrows @ document_questions.js:175
```

Also, in the admin interface, I can see 
* the correct entity kinds
* entity occurances appear to be correct, however when I click on one of them I get an exception (see later)
* Entitys: seems correct
* gazette items: empty as expected
* metadata of the documents is as expected
* ie documents: same error when I click this as the one at entity occurances (see later)
* relations: appears correct

The error I obtain when looking at the information as above is the following
```
ValueError at /admin/corpus/iedocument/
Tree.read(): expected ')' but got 'end-of-string'
            at index 606.
                "...sometoken))"
```
I figured out that the error occurs because there is an unbalanced '(' bracket in the text.
For example, if my document is
```
Hello my name is Gilles (and I like coding.
```
Then I create a fake tree like
```
(ROOT (X Hello) (X my) (X name) (X is) (X Gilles) (X (and) (X I) (X like) (X coding.))
```
I'm guessing that I need to encode the brackets that are part of my tokens, but how should I do this?

**Comment by rafacarrascosa** [comment]
@GilJ It looks like you nailed it. NLP tools (like iepy's default: CoreNLP) usually just replace[0] special characters with tokens that are unlikely to appear by themselves:

 - `(` for `-LRB-` (left round bracket)
 - `[` for `-LSB-` (left square bracket)
 - `{` for `-LCB-` (left curly bracket)
 - ....

If you make these replacements yourself everything should be fine. Perhaps the best place to apply these replacements is just before `set_syntactic_parsing_result` so you can preserve the original unaltered text in all the other places.

[0] In my humble opinion this scheme of replacement is b.lls..t and is hard to believe that a group of CS. PhDs where unable to make a proper serialization of the data (I'm talking about the guys that decided on how annotate the corpora in the first place).

**Comment by GilJ** [comment]
That did solve the second issue I got (the ValueError), but I still have problems with the empty evidence labeling page.

The problem is that there are no entities on the page (```var $eo1 = $(".eo-" + eo_id1);``` returns nothing). Could anyone provide me with some steps or pointers on how to debug this?

**Comment by jmansilla** [comment]
Gilles, you'll have answers for the full team :-)

Very glad to trying to help someone with your motivation and
trouble-fixing skills.

Not sure if this may be something or not, but... before digging issues
on javascript, I would recommend to use the remaining bullets on the
data-model.
Why? Well, because the User-Interface was built assuming that most of
the things on the data models are filled.

I'm arriving a bit late here, apologies for that.

First thing: Did you added lemmatization results? If not, just
providing a list of empty strings (same length than tokens should be
enough).

Next, I read that you added a naive sentence splitter. That's fine.
Now what may be missing is the actual Text-Segmentation.
For reference, here we tried to explain the concepts:
   http://iepy.readthedocs.org/en/latest/preprocess.html#about-the-text-segmentation

So, summarizing, I recommend to have the following preprocess, with
all the steps (some of them naive if desired, some of them not).

- set_tokenization_results
   with input looking like  [(0, 'The'), (4, 'cake'), (9, 'requires'),
(18, '4'), (20, 'eggs'), (25, '.'), (27, 'You'), (31, 'also'), (36,
'need'), (41, 'butter'), (48, '.')]

- set_sentencer_results
   with input looking like [0, 11]

 - set_tagging_results
   with input like ['N', 'Punc', 'Adj', 'V', 'N', 'Prep', 'N',
'-None-', 'Punc', 'N', '-None-', 'Punc', 'Num', 'Adj', 'N',
'-None-', 'Punc', 'Adv', 'Adj', ...]

 - set_lemmatization_results
   with input looking like ['the', 'dog', 'eat', 'chicken']

- set_ner_result
   with input like [FoundEntity(key='cake', kind_name='type',
alias='cake', offset=1, offset_end=2, from_gazette=False),
FoundEntity(key='4', kind_name='number', alias='4', offset=3,
offset_end=4, from_gazette=False),
FoundEntity(key='eggs', kind_name='ingredient', alias='eggs',
offset=4, offset_end=5, from_gazette=False),
FoundEntity(key='butter', kind_name='ingredient', alias='butter',
offset=9, offset_end=10, from_gazette=False)]

- set_syntactic_parsing_result
   with a list of strings (one per sentence) looking each like "(ROOT
(X The) (X cat) (X eats) (X fish) (X .))"
   Note: there is no need to have something smart in here. You can
provide the exact string I just mentioned above for every sentence.

- And finally, you MUST run set_segmentation_result with a no-so-easy
input to describe.
I recommend for this final step to use the vainilla Segmenter, like
its used in here
https://github.com/machinalis/iepy/blob/develop/iepy/instantiation/preprocess.py#L40

Hope it works.
Cheers



-- 
Javier Mansilla - Developer
www.machinalis.com
Skype: javier_mansilla

**Comment by GilJ** [comment]
Hey Javier,

The lemmatization did the trick! I mistakingly assumed that it was optional, as IEPY started rendering some stuff on the front-end. The top of the [preprocess](http://iepy.readthedocs.org/en/latest/preprocess.html) page even states it, although not that clearly :-P.


As for my motivation, I'm working on a thesis on information extraction, and creating relations between my entities was vital (or I would have to take a different approach, which I don't want to).

Thanks for all the help @francolq, @rafacarrascosa, @j0hn and @jmansilla !
